name: themarinator
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 # carousel_pro: ^0.0.13
    #1manStartUpPlugins
    #enables auth
  cloud_firestore: ^0.12.9
  firebase_auth: ^0.15.3

    #no idea yet what this guru finna do
  date_range_picker: ^1.0.3 #no idea fahm  :)
  auto_size_text: ^2.0.2 #this enables texts to auto fill depending on the screen opf the user
  flutter_spinkit: ^3.1.0 #this one is for the loading stuff
  google_sign_in: ^4.0.4 #this one just enables you to sign in via google
  flutter_auth_buttons: ^0.5.0
  international_phone_input: ^1.0.4
  provider: ^3.1.0
  fluttertoast: ^2.2.3

    #mine for the courasel...God help me
  carousel_pro: ^1.0.0
    #ninja plugins
  #enables auth
  #firebase_auth:  ^0.14.0+5
  #cloud_firestore: ^0.12.9+4

    #santos plugins
  #carousel_pro: #^0.0.13
  #firebase_auth: # ^0.6.2+1
  #google_sign_in: #^4.0.2
  #cloud_firestore: #^0.12.5
  #firebase_storage: any
  #fluttertoast: #^2.2.3
  #shared_preferences: #^0.4.3
  #image_picker: #^0.4.10
  #cached_network_image: ^0.5.1
  #intl: ^0.15.7
  #firebase_database:
  #provider: ^3.0.0+1
  #cupertino_icons: ^0.1.2
  #carousel_slider: ^1.3.0
  #flutter_svg: ^0.14.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #below are my previous dependancies
  #cupertino_icons: ^0.1.3
  #carousel_pro: ^1.0.0
  #firebase_auth: ^0.6.2+1
  #firebase_auth: ^0.8.3....this one wa inactive
  #cloud_firestore: ^0.13.5
  #google_sign_in: ^4.0.1+3...this one was inactive
  #google_sign_in: ^4.4.4
  #shared_preferences: ^0.5.8
  #fluttertoast: ^4.0.1
  #firebase_core: 0.4.5

 # firebase_auth: ^0.14.0+5
  #cloud_firestore: ^0.12.9+4

  #firebase_core: ^0.4.5
  #cloud_firestore: ^0.12.9+5
  #firebase_auth: ^0.14.0+5
  #firebase_core: ^0.4.0+9
  #firebase_analytics: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/a4.jpg
    - images/a5.jpg
    - images/a6.jpg
    - images/a9.jpg
    - images/a2.jpg
    - images/a7.jpg
    - images/b1.jpg
    - images/b3.jpg
    - images/b5.jpg
    - images/b6.jpg
    - images/b8.jpg
    - images/b9.jpg
    - images/c6.jpg
    - images/8pm.jpg
    - images/grants.jpg
    - images/hunters.jpg
    - images/william.jpg
    - images/glenfiddich.jpg
    - images/captain.jpg
    - images/b2.png
    - images/b4.png
    - images/logo/c1.jpg
    - images/logo/c2.jpg
    - images/logo/c3.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
